# baseURL = 'https://example.org/'
baseURL = 'https://D1ngyx.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'dingyx-theme'

[markup]
  [markup.highlight] 
    style = "dracula" 
  [markup.tableOfContents]
    startLevel = 2   # ä» h2 å¼€å§‹
    endLevel = 4     # åˆ° h4 ç»“æŸ
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # è®© md èƒ½æ˜¾ç¤ºåŸç”Ÿhtmlå†…å®¹
    
[menu]
  [[menu.main]]
    name = "Home ğŸ "
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts ğŸ“š"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags ğŸ·ï¸"
    url = "/tags/"
    weight = 3